# Generated by Django 4.2.5 on 2023-10-02 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("skus", "0003_alter_subcategory_options"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата продажи")),
                (
                    "sales_type_id",
                    models.PositiveIntegerField(verbose_name="Наличие промо"),
                ),
                (
                    "sales_in_units",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=8,
                        verbose_name="Количество проданных товаров",
                    ),
                ),
                (
                    "promo_sales_in_units",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=8,
                        verbose_name="Количество проданных товаров c промо",
                    ),
                ),
                (
                    "sales_in_rub",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=9,
                        verbose_name="Стоимость проданных товаров, руб.",
                    ),
                ),
                (
                    "promo_sales_in_rub",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=9,
                        verbose_name="Стоимость проданных товаров с промо, руб.",
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="skus.sku",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stores.store",
                        verbose_name="Торговый центр",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продажа товара в супермаркете за сутки",
                "verbose_name_plural": "Продажи товаров в супермаркетах за посуточно",
                "ordering": ["store", "sku", "date"],
                "default_related_name": "sales",
            },
        ),
        migrations.AddConstraint(
            model_name="sale",
            constraint=models.UniqueConstraint(
                fields=("store", "sku", "date"), name="double sale info (unique)"
            ),
        ),
        migrations.AlterIndexTogether(
            name="sale",
            index_together={("store", "sku", "date")},
        ),
    ]
