# Generated by Django 4.2.5 on 2023-10-02 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("skus", "0003_alter_subcategory_options"),
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Forecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата прогноза")),
                (
                    "forecast_data",
                    models.JSONField(
                        default=dict, verbose_name="Прогноз продаж по датам."
                    ),
                ),
                (
                    "sku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="skus.sku",
                        verbose_name="Товар",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stores.store",
                        verbose_name="Торговый центр",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пргноз продаж товара в супермаркете",
                "verbose_name_plural": "Пргноз продаж товаров в супермаркетах",
                "ordering": ["store", "sku", "date"],
                "default_related_name": "forecasts",
            },
        ),
        migrations.AddConstraint(
            model_name="forecast",
            constraint=models.UniqueConstraint(
                fields=("store", "sku", "date"),
                name="double forecast (unique)",
            ),
        ),
        migrations.AlterIndexTogether(
            name="forecast",
            index_together={("store", "sku", "date")},
        ),
    ]
