# Generated by Django 4.2.5 on 2023-10-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forecasts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecast",
            name="next_day_forecast",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Реальные продажи на следующий день"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="forecast",
            name="next_day_real_sale",
            field=models.PositiveIntegerField(
                null=True, verbose_name="Прогноз на следующий день"
            ),
        ),
    ]
