# Generated by Django 4.2.5 on 2023-10-02 10:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("skus", "0002_alter_category_options_alter_group_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subcategory",
            options={
                "ordering": ["subcat_id"],
                "verbose_name": "Подкатегория товара",
                "verbose_name_plural": "Подкатегории товаров",
            },
        ),
    ]
