name: hakathon-lenta workflow
on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
          pip install -r src/requirements.txt
      - name: Test with black
        run: python -m black --diff --check .
      - name: Test with django tests
        run: python ./src/manage.py test ./src/
